language: node_js
node_js:
- '0.12'
- '0.11'
- '0.10'
- iojs
matrix:
  fast_finish: true
before_install:
- npm install -g grunt-cli
script:
- grunt ci
- grunt coveralls:push
env:
  matrix:
    secure: OMJ9PJyQ6vZnOBYpNxjvOvWB//DwhbUjVg7gOtbKUkZxiGrOletCnu0gm1Zt4Jh85Q8LcpZ/rDRuYVC/YLxKPsRW5vCwWfdT5ctYa350+l2KnBN6qRB3D/NP2N+YegFfTAGMA+cVS0E8Hv27aHgED3hs0XTMmwtWPmwx+0ki712XS4rSa9jGxDcioPwXbSmYpRt/2n1zh0d2pC9Wy3j2WH7CnwMFTDq8/hZAL7cLvngMlcI7Sxuox2PPqwoAHSdGOiGULaPFo8iYyqO9kNshKaHEolMbaLl9Pc/kV7pj8t4+r8kMe+cPYD2pMWVW3ZOeKAM//lEhBS+qK7FbWddD3RufQVysIZvvlnThXDJ80LhXyA4hyknXlxAgudsiZLEgWZizh7de8rTxC3ZGnwE+zEo9QWOYmR4dYU0127VxOJLhz+GnMPZ58Csj+XgzBpcKW/AM0S4FxMhv+z6WUYdLxCNkwK9Dzf7/lCPS8PDSURAp0aYmuWqBVvAk89Zvg5M42xaF3CR9BpzwpYdWdwVyf956ntukbX2FuGC0RdNZgiR4V8ptuuJxj5Zh0+e51QrD+Nn38oFERonDOPhib2s7p+2OalcKhS1fO/eSqcSTxYfklTKWC0SPBebNlZoJ2VwXhoo8EErAoeFNqaGOVOmkdOhM1JphBne5Bitl/QF0ZDQ=
deploy:
  provider: npm
  email: simon@simonemms.com
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-db
