language: node_js
node_js:
- node
- '5.11'
- '4.4'
- iojs
- '0.12'
matrix:
  fast_finish: true
sudo: false
script:
- npm run ci
before_deploy:
- npm run build
env:
  matrix:
    secure: OMJ9PJyQ6vZnOBYpNxjvOvWB//DwhbUjVg7gOtbKUkZxiGrOletCnu0gm1Zt4Jh85Q8LcpZ/rDRuYVC/YLxKPsRW5vCwWfdT5ctYa350+l2KnBN6qRB3D/NP2N+YegFfTAGMA+cVS0E8Hv27aHgED3hs0XTMmwtWPmwx+0ki712XS4rSa9jGxDcioPwXbSmYpRt/2n1zh0d2pC9Wy3j2WH7CnwMFTDq8/hZAL7cLvngMlcI7Sxuox2PPqwoAHSdGOiGULaPFo8iYyqO9kNshKaHEolMbaLl9Pc/kV7pj8t4+r8kMe+cPYD2pMWVW3ZOeKAM//lEhBS+qK7FbWddD3RufQVysIZvvlnThXDJ80LhXyA4hyknXlxAgudsiZLEgWZizh7de8rTxC3ZGnwE+zEo9QWOYmR4dYU0127VxOJLhz+GnMPZ58Csj+XgzBpcKW/AM0S4FxMhv+z6WUYdLxCNkwK9Dzf7/lCPS8PDSURAp0aYmuWqBVvAk89Zvg5M42xaF3CR9BpzwpYdWdwVyf956ntukbX2FuGC0RdNZgiR4V8ptuuJxj5Zh0+e51QrD+Nn38oFERonDOPhib2s7p+2OalcKhS1fO/eSqcSTxYfklTKWC0SPBebNlZoJ2VwXhoo8EErAoeFNqaGOVOmkdOhM1JphBne5Bitl/QF0ZDQ=
deploy:
  provider: npm
  email: simon@simonemms.com
  api_key:
    secure: H7j4PViE4B11PTjQybNpAYBm9PNKVgmwnQJmYtVrL3lx7linpZWYRa8jVn7DD3mWGj0KhuOetzjxSjHRb0KnQgKzL5gGvDZaGPu3iABHKwpU/y8VyKCMqKDEQTYN8iu7ZnisDhB1tFom1ByJzKN+IJ+KoA2r7i7BLcUKAtrUerFbQeW09wFNJvnlEGgzUFUqhsvUXENLRgaSqCo8+kOXFLLkBZ1ohyqc4kjrsiXPflNYkKYVq7zYpNX2bLDtpr8Ccgft5GDBUhPBuuYPZGYOqJRLKkiA/vCmM4WapLB1+TqC5TpkNGh9JmBPf5ggzEXgH33V5VmGnjf1vTRNr4cc22X88yAVE/tWLj5rU7lBqmMS7hKX3QHCStLRBkTJjqTEAiwKQMNet6hK+HKkE9AQks+OSKuhIMLuwXht03zcDggpmG7Z9ONKf0sqhx6Zj1ZkWxyT4IubZvu/djlkcGBnqeNr9zq8KJHH9ca5KY+/JihLDb8hNS2QeFnEfGRAM9v5qay8tr4G82FIHXGe53WRxd7bmU79lZUA9Lc2wfAU7IPHq5jo01Z/4WC8IaiA8pPW3MwDBvyrOhokzYN5vXYsj8GtzWtClCBuqr63mARZPQV0SBzYxwxED3E2qQst8nfdZ+uJF0EL4jdoRukgoTp9EiRUz1LKTBOE5TuWlAZcL8A=
  on:
    all_branches: true
    tags: true
    repo: riggerthegeek/steeplejack-db
